In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path 


data_path=Path("/Users/manishasasatte/Downloads/eon_volume_forecasting_python_practice")


consumption=pd.read_csv(data_path/"half_hourly_consumption.csv")
weather = pd.read_csv(data_path / "weather.csv")
customers = pd.read_csv(data_path / "customer_master.csv")
future_weather = pd.read_csv(data_path / "future_weather_forecast.csv")
calendar= pd.read_csv("../data/raw/calendar.csv")
print(consumption.head(3))
print(calendar.head(2))
print(future_weather.head(4))

  customer_id            timestamp  consumption_kwh reading_type
0    CUST0109  2025-01-31 09:00:00           66.727       ACTUAL
1    CUST0021  2025-01-29 23:00:00           69.091       ACTUAL
2    CUST0041  2025-01-27 22:30:00           47.114       ACTUAL
             timestamp        date  settlement_period day_of_week  is_weekend  \
0  2025-01-01 00:00:00  2025-01-01                  1   Wednesday       False
1  2025-01-01 00:30:00  2025-01-01                  2   Wednesday       False

   is_bank_holiday
0             True
1             True
     region            timestamp  forecast_temperature_c  \
0  MIDLANDS  2025-04-01 00:00:00                    8.10
1  MIDLANDS  2025-04-01 00:30:00                   12.42
2  MIDLANDS  2025-04-01 01:00:00                   12.53
3  MIDLANDS  2025-04-01 01:30:00                   10.90

   forecast_wind_speed_mps
0                     3.17
1                     5.80
2                     3.48
3                     4.75

In [9]:
print("Consumption:", consumption.shape)
print("Weather:", weather.shape)
print("Customers:", customers.shape)
print("Calendar:", calendar.shape)
print("Future weather:", future_weather.shape)

Consumption: (120, 8)
Weather: (21600, 5)
Customers: (120, 8)
Calendar: (4320, 6)
Future weather: (3360, 4)

In [29]:
customers.select_dtypes(include=np.number).describe().T

,count,mean,std,min,25%,50%,75%,max
base_load_kwh,120.0,61.384583,34.160439,9.560,27.95000,61.535,95.12750,117.710
temperature_sensitivity,120.0,-0.592050,0.326612,-1.186,-0.86225,-0.584,-0.30375,-0.051
weekend_factor,120.0,0.791775,0.142937,0.553,0.65800,0.803,0.90500,1.048

In [30]:
def data_overview(df, name):
    print("=" * 60)
    print(f"DATASET: {name}")
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nUnique Values:")
    print(df.nunique())

    print("\nFirst 5 Rows:")
    display(df.head())



data_overview(consumption, "Consumption")
data_overview(weather, "Weather")
data_overview(customers, "Customers")
data_overview(future_weather, "Future Weather")
data_overview(calendar, "Calendar")

============================================================
DATASET: Consumption
============================================================

Shape:
(494124, 4)

Columns:
['customer_id', 'timestamp', 'consumption_kwh', 'reading_type']

Data Types:
customer_id            str
timestamp              str
consumption_kwh    float64
reading_type           str
dtype: object

Missing Values:
customer_id        0
timestamp          0
consumption_kwh    0
reading_type       0
dtype: int64

Duplicate Rows:
179

Unique Values:
customer_id           120
timestamp            4320
consumption_kwh    123233
reading_type            2
dtype: int64

First 5 Rows:

  customer_id            timestamp  consumption_kwh reading_type
0    CUST0109  2025-01-31 09:00:00           66.727       ACTUAL
1    CUST0021  2025-01-29 23:00:00           69.091       ACTUAL
2    CUST0041  2025-01-27 22:30:00           47.114       ACTUAL
3    CUST0101  2025-01-14 03:30:00           18.527       ACTUAL
4    CUST0003  2025-03-13 02:30:00           44.826       ACTUAL

============================================================
DATASET: Weather
============================================================

Shape:
(21600, 5)

Columns:
['region', 'timestamp', 'temperature_c', 'wind_speed_mps', 'cloud_cover_pct']

Data Types:
region                 str
timestamp              str
temperature_c      float64
wind_speed_mps     float64
cloud_cover_pct    float64
dtype: object

Missing Values:
region              0
timestamp           0
temperature_c      70
wind_speed_mps      0
cloud_cover_pct     0
dtype: int64

Duplicate Rows:
0

Unique Values:
region                5
timestamp          4320
temperature_c      1576
wind_speed_mps      996
cloud_cover_pct    1062
dtype: int64

First 5 Rows:

,region,timestamp,temperature_c,wind_speed_mps,cloud_cover_pct
0,MIDLANDS,2025-01-01 00:00:00,6.01,3.64,55.4
1,MIDLANDS,2025-01-01 00:30:00,5.52,4.41,41.8
2,MIDLANDS,2025-01-01 01:00:00,6.08,5.33,66.9
3,MIDLANDS,2025-01-01 01:30:00,5.90,4.59,96.6
4,MIDLANDS,2025-01-01 02:00:00,4.61,3.39,46.4

============================================================
DATASET: Customers
============================================================

Shape:
(120, 8)

Columns:
['customer_id', 'segment', 'region', 'base_load_kwh', 'temperature_sensitivity', 'weekend_factor', 'active_from', 'active_to']

Data Types:
customer_id                    str
segment                        str
region                         str
base_load_kwh              float64
temperature_sensitivity    float64
weekend_factor             float64
active_from                    str
active_to                      str
dtype: object

Missing Values:
customer_id                  0
segment                      0
region                       0
base_load_kwh                0
temperature_sensitivity      0
weekend_factor               0
active_from                  0
active_to                  112
dtype: int64

Duplicate Rows:
0

Unique Values:
customer_id                120
segment                      4
region                       5
base_load_kwh              118
temperature_sensitivity    116
weekend_factor             109
active_from                  8
active_to                    7
dtype: int64

First 5 Rows:

,customer_id,segment,region,base_load_kwh,temperature_sensitivity,weekend_factor,active_from,active_to
0,CUST0001,Commercial,MIDLANDS,107.77,-0.304,0.878,2024-01-01,NaN
1,CUST0002,Industrial,SOUTH,108.07,-1.045,0.568,2024-01-01,NaN
2,CUST0003,Commercial,MIDLANDS,66.11,-0.584,0.553,2024-01-01,NaN
3,CUST0004,Commercial,SCOTLAND,43.38,-0.609,0.576,2024-01-01,NaN
4,CUST0005,SME,SCOTLAND,94.47,-0.214,0.853,2024-01-01,NaN

============================================================
DATASET: Future Weather
============================================================

Shape:
(3360, 4)

Columns:
['region', 'timestamp', 'forecast_temperature_c', 'forecast_wind_speed_mps']

Data Types:
region                         str
timestamp                      str
forecast_temperature_c     float64
forecast_wind_speed_mps    float64
dtype: object

Missing Values:
region                     0
timestamp                  0
forecast_temperature_c     0
forecast_wind_speed_mps    0
dtype: int64

Duplicate Rows:
0

Unique Values:
region                        5
timestamp                   672
forecast_temperature_c     1118
forecast_wind_speed_mps     793
dtype: int64

First 5 Rows:

,region,timestamp,forecast_temperature_c,forecast_wind_speed_mps
0,MIDLANDS,2025-04-01 00:00:00,8.10,3.17
1,MIDLANDS,2025-04-01 00:30:00,12.42,5.80
2,MIDLANDS,2025-04-01 01:00:00,12.53,3.48
3,MIDLANDS,2025-04-01 01:30:00,10.90,4.75
4,MIDLANDS,2025-04-01 02:00:00,10.35,2.56

============================================================
DATASET: Calendar
============================================================

Shape:
(4320, 6)

Columns:
['timestamp', 'date', 'settlement_period', 'day_of_week', 'is_weekend', 'is_bank_holiday']

Data Types:
timestamp              str
date                   str
settlement_period    int64
day_of_week            str
is_weekend            bool
is_bank_holiday       bool
dtype: object

Missing Values:
timestamp            0
date                 0
settlement_period    0
day_of_week          0
is_weekend           0
is_bank_holiday      0
dtype: int64

Duplicate Rows:
0

Unique Values:
timestamp            4320
date                   90
settlement_period      48
day_of_week             7
is_weekend              2
is_bank_holiday         2
dtype: int64

First 5 Rows:

,timestamp,date,settlement_period,day_of_week,is_weekend,is_bank_holiday
0,2025-01-01 00:00:00,2025-01-01,1,Wednesday,False,True
1,2025-01-01 00:30:00,2025-01-01,2,Wednesday,False,True
2,2025-01-01 01:00:00,2025-01-01,3,Wednesday,False,True
3,2025-01-01 01:30:00,2025-01-01,4,Wednesday,False,True
4,2025-01-01 02:00:00,2025-01-01,5,Wednesday,False,True

In [34]:
consumption["customer_id"].nunique()

120

In [37]:
consumption["reading_type"].unique()

<ArrowStringArray>
['ACTUAL', 'ESTIMATED']
Length: 2, dtype: str

In [35]:
consumption

       customer_id            timestamp  consumption_kwh reading_type
0         CUST0109  2025-01-31 09:00:00           66.727       ACTUAL
1         CUST0021  2025-01-29 23:00:00           69.091       ACTUAL
2         CUST0041  2025-01-27 22:30:00           47.114       ACTUAL
3         CUST0101  2025-01-14 03:30:00           18.527       ACTUAL
4         CUST0003  2025-03-13 02:30:00           44.826       ACTUAL
...            ...                  ...              ...          ...
494119    CUST0056  2025-03-30 04:30:00           50.056       ACTUAL
494120    CUST0031  2025-03-19 14:00:00           75.154       ACTUAL
494121    CUST0005  2025-03-08 12:30:00           57.393       ACTUAL
494122    CUST0005  2025-01-29 10:30:00           78.568       ACTUAL
494123    CUST0072  2025-02-09 18:30:00          135.503       ACTUAL

[494124 rows x 4 columns]

In [38]:
consumption['reading_type'].value_counts(dropna=False)

reading_type
ACTUAL       493624
ESTIMATED       500
Name: count, dtype: int64

In [41]:

print("Number of exact duplicate rows:",
      consumption.duplicated().sum())

Number of exact duplicate rows: 179

In [56]:
records_per_customer = consumption["customer_id"].value_counts()

records_per_customer.value_counts().sort_index()

count
1681     1
1874     1
1921     1
2110     1
2260     1
2303     2
2834     1
2975     1
2977     1
3071     1
3407     1
3695     1
3696     1
3889     1
3981     1
4312     1
4313     2
4314     2
4315     3
4316     8
4317    13
4318    22
4319    15
4320    16
4321     7
4322     8
4323     6
4325     1
Name: count, dtype: int64

In [ ]:
consumption.dtypes

customer_id            str
timestamp              str
consumption_kwh    float64
reading_type           str
dtype: object

In [64]:
consumption["timestamp"]=pd.to_datetime(consumption["timestamp"],errors="coerce")

consumption["timestamp"].isnull().sum()

np.int64(0)

In [65]:
consumption.describe()

                        timestamp  consumption_kwh
count                      494124    494124.000000
mean   2025-02-14 23:01:22.571581        53.750720
min           2025-01-01 00:00:00      -176.369000
25%           2025-01-23 17:00:00        26.406000
50%           2025-02-14 22:30:00        47.738000
75%           2025-03-09 05:00:00        73.645000
max           2025-03-31 23:30:00      1056.151754
std                           NaN        33.319597

In [79]:
consumption[
    consumption["consumption_kwh"] == 0
].shape

(384, 4)

In [84]:
consumption["timestamp"].min()
consumption["timestamp"].max()

Timestamp('2025-03-31 23:30:00')

In [92]:
# we storted this sorted_cons df
consumption=consumption.sort_values(["customer_id","timestamp"])
consumption

       customer_id           timestamp  consumption_kwh reading_type
27088     CUST0001 2025-01-01 00:00:00           77.072       ACTUAL
63268     CUST0001 2025-01-01 00:30:00           77.936       ACTUAL
449889    CUST0001 2025-01-01 01:00:00           80.436       ACTUAL
122603    CUST0001 2025-01-01 01:30:00           77.071       ACTUAL
197951    CUST0001 2025-01-01 02:00:00           74.595       ACTUAL
...            ...                 ...              ...          ...
213587    CUST0120 2025-03-31 21:30:00           59.326       ACTUAL
96927     CUST0120 2025-03-31 22:00:00           65.732       ACTUAL
410249    CUST0120 2025-03-31 22:30:00           58.121       ACTUAL
39661     CUST0120 2025-03-31 23:00:00           62.640       ACTUAL
391411    CUST0120 2025-03-31 23:30:00           56.582       ACTUAL

[494124 rows x 4 columns]

In [93]:
# after  sorting  this sorted_cons df we nedd to resrte the index
consumption =consumption.reset_index(drop=True)
consumption

       customer_id           timestamp  consumption_kwh reading_type
0         CUST0001 2025-01-01 00:00:00           77.072       ACTUAL
1         CUST0001 2025-01-01 00:30:00           77.936       ACTUAL
2         CUST0001 2025-01-01 01:00:00           80.436       ACTUAL
3         CUST0001 2025-01-01 01:30:00           77.071       ACTUAL
4         CUST0001 2025-01-01 02:00:00           74.595       ACTUAL
...            ...                 ...              ...          ...
494119    CUST0120 2025-03-31 21:30:00           59.326       ACTUAL
494120    CUST0120 2025-03-31 22:00:00           65.732       ACTUAL
494121    CUST0120 2025-03-31 22:30:00           58.121       ACTUAL
494122    CUST0120 2025-03-31 23:00:00           62.640       ACTUAL
494123    CUST0120 2025-03-31 23:30:00           56.582       ACTUAL

[494124 rows x 4 columns]

In [97]:
duplicate_readings = consumption[
    consumption.duplicated(
        subset=["customer_id", "timestamp"],
        keep=False
    )
]
duplicate_readings

       customer_id           timestamp  consumption_kwh reading_type
885       CUST0001 2025-01-19 10:30:00          101.225       ACTUAL
886       CUST0001 2025-01-19 10:30:00          101.225       ACTUAL
6043      CUST0002 2025-02-05 22:00:00          124.627       ACTUAL
6044      CUST0002 2025-02-05 22:00:00          124.627       ACTUAL
9306      CUST0003 2025-01-14 22:00:00           58.627       ACTUAL
...            ...                 ...              ...          ...
492323    CUST0120 2025-02-22 12:30:00           73.128       ACTUAL
493058    CUST0120 2025-03-09 20:00:00           69.519       ACTUAL
493059    CUST0120 2025-03-09 20:00:00           69.519       ACTUAL
493238    CUST0120 2025-03-13 13:30:00           68.005       ACTUAL
493239    CUST0120 2025-03-13 13:30:00           68.005       ACTUAL

[358 rows x 4 columns]

In [101]:
# Step 11 — Check missing values again
consumption.isnull().sum()
negative_consumption = consumption[
    consumption["consumption_kwh"] < 0
]
negative_consumption

zero_consumption = consumption[
    consumption["consumption_kwh"] == 0
]

zero_consumption.head()

      customer_id           timestamp  consumption_kwh reading_type
56008    CUST0014 2025-02-10 00:00:00              0.0       ACTUAL
56009    CUST0014 2025-02-10 00:30:00              0.0       ACTUAL
56010    CUST0014 2025-02-10 01:00:00              0.0       ACTUAL
56011    CUST0014 2025-02-10 01:30:00              0.0       ACTUAL
56012    CUST0014 2025-02-10 02:00:00              0.0       ACTUAL

In [102]:
consumption["time_difference"] =consumption.groupby("customer_id")["timestamp"].diff()
consumption["time_difference"]

0                    NaT
1        0 days 00:30:00
2        0 days 00:30:00
3        0 days 00:30:00
4        0 days 00:30:00
               ...
494119   0 days 00:30:00
494120   0 days 00:30:00
494121   0 days 00:30:00
494122   0 days 00:30:00
494123   0 days 00:30:00
Name: time_difference, Length: 494124, dtype: timedelta64[us]

In [103]:
consumption["time_difference"].value_counts().head(10)

time_difference
0 days 00:30:00    493506
0 days 01:00:00       319
0 days 00:00:00       179
Name: count, dtype: int64

In [ ]:
# Date  features
consumption["date"]=consumption["timestamp"].dt.date
consumption["year"]=consumption["timestamp"].dt.year
consumption["month"]=consumption["timestamp"].dt.month
consumption["day"]=consumption["timestamp"].dt.day
consumption["hour"]=consumption["timestamp"].dt.hour
consumption["minute"]=consumption["timestamp"].dt.minute
consumption["day_of_week"]=consumption["timestamp"].dt.day_of_week
consumption["day_name"]=consumption["timestamp"].dt.day_name()


consumption

,customer_id,timestamp,consumption_kwh,reading_type,time_difference,date,year,month,day,day_of_week,day_name,hour,minute
0,CUST0001,2025-01-01 00:00:00,77.072,ACTUAL,NaT,2025-01-01,2025,1,1,2,Wednesday,0,0
1,CUST0001,2025-01-01 00:30:00,77.936,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,0,30
2,CUST0001,2025-01-01 01:00:00,80.436,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,0
3,CUST0001,2025-01-01 01:30:00,77.071,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,30
4,CUST0001,2025-01-01 02:00:00,74.595,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494119,CUST0120,2025-03-31 21:30:00,59.326,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,21,30
494120,CUST0120,2025-03-31 22:00:00,65.732,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,0
494121,CUST0120,2025-03-31 22:30:00,58.121,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,30
494122,CUST0120,2025-03-31 23:00:00,62.640,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,0
494123,CUST0120,2025-03-31 23:30:00,56.582,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,30

In [ ]:
consumption[(consumption["customer_id"]=="CUST0001" ) & (consumption["date"] == pd.to_datetime("2025-01-01").date())].count()

customer_id        48
timestamp          48
consumption_kwh    48
reading_type       48
time_difference    47
date               48
year               48
month              48
day                48
day_of_week        48
day_name           48
hour               48
minute             48
dtype: int64

In [118]:
consumption["settlement_period"]=consumption["hour"]*2+consumption["minute"]//30+1
consumption

,customer_id,timestamp,consumption_kwh,reading_type,time_difference,date,year,month,day,day_of_week,day_name,hour,minute,settlement_period
0,CUST0001,2025-01-01 00:00:00,77.072,ACTUAL,NaT,2025-01-01,2025,1,1,2,Wednesday,0,0,1
1,CUST0001,2025-01-01 00:30:00,77.936,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,0,30,2
2,CUST0001,2025-01-01 01:00:00,80.436,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,0,3
3,CUST0001,2025-01-01 01:30:00,77.071,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,30,4
4,CUST0001,2025-01-01 02:00:00,74.595,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,2,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494119,CUST0120,2025-03-31 21:30:00,59.326,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,21,30,44
494120,CUST0120,2025-03-31 22:00:00,65.732,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,0,45
494121,CUST0120,2025-03-31 22:30:00,58.121,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,30,46
494122,CUST0120,2025-03-31 23:00:00,62.640,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,0,47
494123,CUST0120,2025-03-31 23:30:00,56.582,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,30,48

In [120]:
consumption

,customer_id,timestamp,consumption_kwh,reading_type,time_difference,date,year,month,day,day_of_week,day_name,hour,minute,settlement_period
0,CUST0001,2025-01-01 00:00:00,77.072,ACTUAL,NaT,2025-01-01,2025,1,1,2,Wednesday,0,0,1
1,CUST0001,2025-01-01 00:30:00,77.936,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,0,30,2
2,CUST0001,2025-01-01 01:00:00,80.436,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,0,3
3,CUST0001,2025-01-01 01:30:00,77.071,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,1,30,4
4,CUST0001,2025-01-01 02:00:00,74.595,ACTUAL,0 days 00:30:00,2025-01-01,2025,1,1,2,Wednesday,2,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494119,CUST0120,2025-03-31 21:30:00,59.326,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,21,30,44
494120,CUST0120,2025-03-31 22:00:00,65.732,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,0,45
494121,CUST0120,2025-03-31 22:30:00,58.121,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,22,30,46
494122,CUST0120,2025-03-31 23:00:00,62.640,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,0,47
494123,CUST0120,2025-03-31 23:30:00,56.582,ACTUAL,0 days 00:30:00,2025-03-31,2025,3,31,0,Monday,23,30,48

In [119]:
consumption["settlement_period"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
      dtype=int32)

In [123]:
consumption.to_csv('../data/processed/consumption_cleaned.csv')

In [ ]:
df=pd.read_csv("Data-Science-Portfolio-Projects/Energy_Forcasting/data/processed/model_features.csv")
df